server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.10.206:3306/nanwe_pushDb?useSSL=false&serverTimezone=Asia/Seoul
    username: nauri
    password: skdnfl00@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.nanwe.push.entity,com.nanwe.push.dto

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
