server:
  port: 8080

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    header: Authorization
    secret:
    token-validity-in-seconds: 86400

mybatis:
  mapper-locations:
  type-aliases-package:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
